In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

In [5]:
ESERCIZI = pd.read_csv('../Dataset/Comune-di-Milano-Pubblici-esercizi(in)-2.csv',sep=';',encoding='utf-8')
ESERCIZI

þÿTipo esercizio storico pe              Insegna  \
0                                NaN                  NaN   
1                                NaN                  NaN   
2                                NaN                  NaN   
3                                NaN                  NaN   
4                                NaN                  NaN   
...                              ...                  ...   
6899  wine,birr.,pub enot.,caff.,the           bar cherry   
6900  wine,birr.,pub enot.,caff.,the            la balusa   
6901  wine,birr.,pub enot.,caff.,the  la champagnerie sas   
6902  wine,birr.,pub enot.,caff.,the          old rooster   
6903  wine,birr.,pub enot.,caff.,the            starhotel   

                                             Ubicazione Tipo via  \
0     ALZ NAVIGLIO GRANDE N. 12 ; isolato:057; (z.d. 6)      ALZ   
1                    ALZ NAVIGLIO GRANDE N. 44 (z.d. 6)      ALZ   
2                    ALZ NAVIGLIO GRANDE N. 48 (z.d. 6)      ALZ   
3                     ALZ NAVIGLIO GRANDE N. 8 (z.d. 6)      ALZ   
4                    ALZ NAVIGLIO PAVESE N. 24 (z.d. 6)      ALZ   
...                                                 ...      ...   
6899  VLE DORIA ANDREA N. 12 ; isolato:031; accesso:...      VLE   
6900  VIA GARIGLIANO N. 5 ; isolato:277; accesso: ac...      VIA   
6901  VIA SOTTOCORNO PASQUALE N. 4 ; isolato:014; ac...      VIA   
6902  VIA CASTROVILLARI N. 23 ; isolato:150; accesso...      VIA   
6903        PZA FONTANA N. 3 ;pza fontana 003; (z.d. 1)      PZA   

          Descrizione via Civico  Codice via  ZD        Forma commercio  \
0         NAVIGLIO GRANDE     12        5144   6                    NaN   
1         NAVIGLIO GRANDE     44        5144   6                    NaN   
2         NAVIGLIO GRANDE     48        5144   6                    NaN   
3         NAVIGLIO GRANDE      8        5144   6                    NaN   
4         NAVIGLIO PAVESE     24        5161   6                    NaN   
...                   ...    ...         ...  ..                    ...   
6899         DORIA ANDREA     12        2230   2  solo somministrazione   
6900           GARIGLIANO      5        1134   9  solo somministrazione   
6901  SOTTOCORNO PASQUALE      4        3152   4  solo somministrazione   
6902        CASTROVILLARI     23        6299   7  solo somministrazione   
6903              FONTANA      3         308   1  solo somministrazione   

     Forma commercio prev Forma vendita  \
0                     NaN           NaN   
1                     NaN           NaN   
2                     NaN           NaN   
3                     NaN           NaN   
4                     NaN           NaN   
...                   ...           ...   
6899     somministrazione         misto   
6900     somministrazione         misto   
6901     somministrazione         misto   
6902     somministrazione         misto   
6903     somministrazione         misto   

                                     Settore storico pe  \
0     Ristorante, trattoria, osteria;Genere Merceol....   
1                             Bar gastronomici e simili   
2                             Bar gastronomici e simili   
3     BAR CAFFÿý E SIMILI;Ristorante, trattoria, ost...   
4                             Bar gastronomici e simili   
...                                                 ...   
6899                     Wine,birr.,pub enot.,caff.,the   
6900                     Wine,birr.,pub enot.,caff.,the   
6901      BAR CAFFÿý E SIMILI;Bar gastronomici e simili   
6902                     Wine,birr.,pub enot.,caff.,the   
6903                     Wine,birr.,pub enot.,caff.,the   

      Superficie somministrazione  
0                            83.0  
1                            26.0  
2                            58.0  
3                           101.0  
4                            51.0  
...                           ...  
6899                         59.0  
6900                         40.0  
6901    

In [8]:
# Understand the shape of the dataset
ESERCIZI.shape

(6904, 13)

In [9]:
# Printing the columns
ESERCIZI.columns

Index(['þÿTipo esercizio storico pe', 'Insegna', 'Ubicazione', 'Tipo via',
       'Descrizione via', 'Civico', 'Codice via', 'ZD', 'Forma commercio',
       'Forma commercio prev', 'Forma vendita', 'Settore storico pe',
       'Superficie somministrazione'],
      dtype='object')

In [11]:
# Understand the types of data
ESERCIZI.dtypes

þÿTipo esercizio storico pe     object
Insegna                         object
Ubicazione                      object
Tipo via                        object
Descrizione via                 object
Civico                          object
Codice via                       int64
ZD                               int64
Forma commercio                 object
Forma commercio prev            object
Forma vendita                   object
Settore storico pe              object
Superficie somministrazione    float64
dtype: object

In [12]:
#Try to understand the different types of exercise's types there are
ESERCIZI['þÿTipo esercizio storico pe'].unique()

array([nan, 'bar caffÿý', "bar-caffe' e simili",
       'bar gastronomici e simili', 'bar pasticc.gelat.crem.creper.',
       'birreria', 'cibi cotti', 'cibi cotti preconfezionati',
       'gelateria', 'genere merceol.autorizz.sanit.', 'mensa', 'osteria',
       'pizzeria', 'pizzerie e simili', 'prodotti di gastronomia',
       'ristorante', 'ristorante, trattoria, osteria',
       'sale da ballo, locali notturni', 'spaccio bevande analcoliche',
       'tav.calde,self service,fast f.', 'tavola calda', 'tavola fredda',
       'trattoria', 'wine,birr.,pub enot.,caff.,the'], dtype=object)

In [13]:
ESERCIZI['Descrizione via'].unique()

array(['NAVIGLIO GRANDE', 'NAVIGLIO PAVESE', 'DI PORTA NUOVA', ...,
       'PAPA DARIO', 'SIBARI', 'CASTROVILLARI'],
      shape=(1840,), dtype=object)

In [14]:
ESERCIZI['Forma commercio'].unique()

array([nan, 'solo somministrazione', 'somministrazione/minuto'],
      dtype=object)

In [15]:
ESERCIZI['Forma commercio prev'].unique()

array([nan, 'somministrazione', 'minuto'], dtype=object)

In [17]:
ESERCIZI['Forma vendita'].unique()

array([nan, 'misto', 'al banco', 'al tavolo', 'self service'],
      dtype=object)

In [18]:
ESERCIZI['Settore storico pe'].unique()

array(['Ristorante, trattoria, osteria;Genere Merceol.Autorizz.Sanit.;Ristorante',
       'Bar gastronomici e simili',
       'BAR CAFFÿý E SIMILI;Ristorante, trattoria, osteria', ...,
       "LETT. GIOCHI LECITI + SOCIETA';Genere Merceol.Autorizz.Sanit.;Trattoria;Ristorante, trattoria, osteria",
       'Disco-piano-americ.bar serali;Trattoria;BAR CAFFÿý E SIMILI;Pizzerie e simili;Ristorante, trattoria, osteria;Pizzeria;Genere Merceol.Autorizz.Sanit.',
       'Tavola calda;Pizzeria;Ristorante, trattoria, osteria;Trattoria;Genere Merceol.Autorizz.Sanit.'],
      shape=(3976,), dtype=object)

In [21]:
# Grouping by 'Codice Via' and counting
via_count = ESERCIZI['Codice via'].value_counts().sort_index()

74

In [22]:
# If needed, here group by other columns



In [24]:
# Look for duplicates
duplicates = ESERCIZI.duplicated()
duplicates.any()

np.True_

In [26]:
# Duplicates have been found, print them
ESERCIZI[duplicates]
#Only one has been found at the moment

þÿTipo esercizio storico pe Insegna                  Ubicazione Tipo via  \
940                         NaN     NaN  VIA SALASCO N. 29 (z.d. 5)      VIA   

    Descrizione via Civico  Codice via  ZD Forma commercio  \
940         SALASCO     29        4051   5             NaN   

    Forma commercio prev Forma vendita           Settore storico pe  \
940                  NaN           NaN  Spaccio bevande analcoliche   

     Superficie somministrazione  
940                          NaN

In [27]:
# Look for null values
ESERCIZI.isnull()

þÿTipo esercizio storico pe  Insegna  Ubicazione  Tipo via  \
0                            True     True       False     False   
1                            True     True       False     False   
2                            True     True       False     False   
3                            True     True       False     False   
4                            True     True       False     False   
...                           ...      ...         ...       ...   
6899                        False    False       False     False   
6900                        False    False       False     False   
6901                        False    False       False     False   
6902                        False    False       False     False   
6903                        False    False       False     False   

      Descrizione via  Civico  Codice via     ZD  Forma commercio  \
0               False   False       False  False             True   
1               False   False       False  False             True   
2               False   False       False  False             True   
3               False   False       False  False             True   
4               False   False       False  False             True   
...               ...     ...         ...    ...              ...   
6899            False   False       False  False            False   
6900            False   False       False  False            False   
6901            False   False       False  False            False   
6902            False   False       False  False            False   
6903            False   False       False  False            False   

      Forma commercio prev  Forma vendita  Settore storico pe  \
0                     True           True               False   
1                     True           True               False   
2                     True           True               False   
3                     True           True               False   
4                     True           True               False   
...                    ...            ...                 ...   
6899                 False          False               False   
6900                 False          False               False   
6901                 False          False               False   
6902                 False          False               False   
6903                 False          False               False   

      Superficie somministrazione  
0                           False  
1                           False  
2                           False  
3                           False  
4                           False  
...                           ...  
6899                        False  
6900                        False  
6901                        False  
6902                        False  
6903                        False  

[6904 rows x 13 columns]

In [28]:
nulls = {}
for col in ESERCIZI.columns:
    nulls[col] = ESERCIZI[col].isnull().sum()
    
print(nulls)

{'þÿTipo esercizio storico pe': np.int64(1353), 'Insegna': np.int64(3410), 'Ubicazione': np.int64(0), 'Tipo via': np.int64(0), 'Descrizione via': np.int64(0), 'Civico': np.int64(156), 'Codice via': np.int64(0), 'ZD': np.int64(0), 'Forma commercio': np.int64(1571), 'Forma commercio prev': np.int64(1397), 'Forma vendita': np.int64(1424), 'Settore storico pe': np.int64(21), 'Superficie somministrazione': np.int64(79)}


In [29]:
# Number of not null values. Clearly there are some many null values in 'Insegna'
ESERCIZI.count()

þÿTipo esercizio storico pe    5551
Insegna                        3494
Ubicazione                     6904
Tipo via                       6904
Descrizione via                6904
Civico                         6748
Codice via                     6904
ZD                             6904
Forma commercio                5333
Forma commercio prev           5507
Forma vendita                  5480
Settore storico pe             6883
Superficie somministrazione    6825
dtype: int64

In [36]:
# Perform the completeness evaluation:
total_values = ESERCIZI.shape[0] * ESERCIZI.shape[1]
total_values

89752

In [37]:
not_nulls = ESERCIZI.count().sum()
not_nulls

np.int64(80341)

In [40]:
completeness = not_nulls / total_values
print(f"{completeness*100:.2f}%") 
# 89.51%

89.51%


In [43]:
# Dive deeper on the 'Insegna' column. it is 50.61%!!! Extremely low!!
rows = ESERCIZI.shape[0]
non_nulls_insegna = ESERCIZI['Insegna'].count()
completeness_insegna = non_nulls_insegna / rows
print(f"{completeness_insegna*100:.2f}%") 

50.61%


In [44]:
# Compute the completeness without the column 'Insegna'
dataset_without_insegna = ESERCIZI.drop(columns=['Insegna'])
total_values_without_insegna = dataset_without_insegna.shape[0]*dataset_without_insegna.shape[1]
non_nulls_without_insegna = dataset_without_insegna.count().sum()
completeness_without_insegna = non_nulls_without_insegna / total_values_without_insegna
print(f"{completeness_without_insegna*100:.2f}%")

92.76%


In [45]:
# Accuracy - not able to assess it


In [47]:
# Consistency, check if all the values in 'Civico' and 'Superficie' are numerical
superficie_consistency = pd.to_numeric(ESERCIZI['Superficie somministrazione'], errors='coerce').notna().mean()
superficie_consistency

np.float64(0.9885573580533025)

In [48]:
invalid_rows = ESERCIZI[pd.to_numeric(ESERCIZI['Superficie somministrazione'], errors='coerce').isna()]
invalid_rows

þÿTipo esercizio storico pe Insegna  \
33                           NaN     NaN   
44                           NaN     NaN   
75                           NaN     NaN   
78                           NaN     NaN   
99                           NaN     NaN   
...                          ...     ...   
1287                         NaN     NaN   
1317                         NaN     NaN   
1320                         NaN     NaN   
4891                    pizzeria     NaN   
5246                  ristorante     NaN   

                                             Ubicazione Tipo via  \
33                            CSO EUROPA N. 18 (z.d. 1)      CSO   
44                CSO GARIBALDI GIUSEPPE N. 81 (z.d. 1)      CSO   
75                         GLL PASSARELLA N. 2 (z.d. 1)      GLL   
78                            LGO CAIROLI N. 2 (z.d. 1)      LGO   
99                               PLE SUSA N. 4 (z.d. 4)      PLE   
...                                                 ...      ...   
1287                       VLE SARCA num.000 ; (z.d. 9)      PLE   
1317                          VLE UMBRIA N. 27 (z.d. 4)      VLE   
1320                        VLE UNGHERIA N. 10 (z.d. 4)      VLE   
4891  VIA CASTEL MORRONE N. 7 ; isolato:049; accesso...      VIA   
5246  CSO DI PORTA ROMANA N. 120 ; isolato:118; (z.d...      CSO   

         Descrizione via Civico  Codice via  ZD          Forma commercio  \
33                EUROPA     18         300   1                      NaN   
44    GARIBALDI GIUSEPPE     81        1010   1                      NaN   
75            PASSARELLA      2         303   1                      NaN   
78               CAIROLI      2         710   1                      NaN   
99                  SUSA      4        3101   4                      NaN   
...                  ...    ...         ...  ..                      ...   
1287              LUGANO     35        1238   9                      NaN   
1317              UMBRIA     27        3145   4                      NaN   
1320            UNGHERIA     10        3357   4                      NaN   
4891      CASTEL MORRONE      7        3185   3  somministrazione/minuto   
5246     DI PORTA ROMANA    120         402   1                      NaN   

     Forma commercio prev Forma vendita  \
33                    NaN           NaN   
44                    NaN           NaN   
75                    NaN           NaN   
78                    NaN           NaN   
99                    NaN           NaN   
...                   ...           ...   
1287                  NaN           NaN   
1317                  NaN           NaN   
1320                  NaN           NaN   
4891     somministrazione         misto   
5246                  NaN           NaN   

                                     Settore storico pe  \
33                       Genere Merceol.Autorizz.Sanit.   
44                       Genere Merceol.Autorizz.Sanit.   
75                                Ristorante;BAR CAFFÿý   
78                                           Ristorante   
99                                                  NaN   
...                                                 ...   
1287                              BAR CAFFÿý;Ristorante   
1317                            Tavola calda;BAR CAFFÿý   
1320                            Tavola calda;BAR CAFFÿý   
4891  Pizzerie e simili;Genere Merceol.Autorizz.Sani...   
5246          Ristorante;Genere Merceol.Autorizz.Sanit.   

      Superficie somministrazione  
33                            NaN  
44                            NaN  
75                            NaN  
78                            NaN  
99                            NaN  
...                           ...  
1287                          NaN  
1317                          NaN  
1320                          NaN  
4891                          NaN  
5246                          NaN  

[79 rows x 13 columns]

In [52]:

rows = ESERCIZI.shape[0]
non_nulls_sup = ESERCIZI['Superficie somministrazione'].count()
print(f"{rows-non_nulls_sup}")

79


Superficie is consistent as all the rows that are not numeric are just nulls. 