In [1]:
import pandas as pd
import numpy as np

In [2]:
MILANO = pd.read_csv('../Dataset/Comune-di-Milano-Pubblici-esercizi(in)-2.csv',sep=';',encoding='utf-8')

In [4]:
MILANO[["Forma commercio prev", "Forma commercio", "Forma vendita"]]

Forma commercio prev        Forma commercio Forma vendita
0                     NaN                    NaN           NaN
1                     NaN                    NaN           NaN
2                     NaN                    NaN           NaN
3                     NaN                    NaN           NaN
4                     NaN                    NaN           NaN
...                   ...                    ...           ...
6899     somministrazione  solo somministrazione         misto
6900     somministrazione  solo somministrazione         misto
6901     somministrazione  solo somministrazione         misto
6902     somministrazione  solo somministrazione         misto
6903     somministrazione  solo somministrazione         misto

[6904 rows x 3 columns]

In [5]:
MILANO["Forma commercio"].unique()

array([nan, 'solo somministrazione', 'somministrazione/minuto'],
      dtype=object)

In [6]:
MILANO["Forma commercio prev"].unique()

array([nan, 'somministrazione', 'minuto'], dtype=object)

In [7]:
MILANO["Forma vendita"].unique()

array([nan, 'misto', 'al banco', 'al tavolo', 'self service'],
      dtype=object)

In [10]:
MILANO[MILANO["Forma commercio"] == "somministrazione/minuto"]

þÿTipo esercizio storico pe                    Insegna  \
1337                         NaN              bar sunflower   
1358                  bar caffÿý                        NaN   
1359                  bar caffÿý                        NaN   
1360                  bar caffÿý                        NaN   
1361                  bar caffÿý                        NaN   
...                          ...                        ...   
6683                   trattoria             free time cafe   
6731                   trattoria               lo  scarabeo   
6760                   trattoria              osteria ma.si   
6811                   trattoria   rist. pizz. la rosa nera   
6855                   trattoria  trattoria bolognese da m.   

                                             Ubicazione Tipo via  \
1337  CSO MAGENTA N. 78 ;via verri pietro 008; isola...      CSO   
1358  CSO BUENOS AIRES N. 2 ; isolato:143; accesso: ...      CSO   
1359  CSO BUENOS AIRES N. 49 ; isolato:044; accesso:...      CSO   
1360  CSO BUENOS AIRES N. 59 int. centro comm. le co...      CSO   
1361  CSO BUENOS AIRES N. 75 ; isolato:007; accesso:...      CSO   
...                                                 ...      ...   
6683  VIA BIANCONI CARLO N. 7 ; isolato:109; accesso...      VIA   
6731  VIA GOVONE GIUSEPPE N. 29 ; isolato:013; acces...      VIA   
6760  VIA LODOVICO IL MORO N. 93 ; isolato:013; acce...      VIA   
6811  VIA SOLFERINO N. 12 ; isolato:247; accesso: ac...      VIA   
6855  VIA LOMBARDINI ELIA N. 14 ; isolato:063; acces...      VIA   

       Descrizione via Civico  Codice via  ZD          Forma commercio  \
1337           MAGENTA     78         604   1  somministrazione/minuto   
1358      BUENOS AIRES      2        2129   3  somministrazione/minuto   
1359      BUENOS AIRES     49        2129   3  somministrazione/minuto   
1360      BUENOS AIRES     59        2129   3  somministrazione/minuto   
1361      BUENOS AIRES     75        2129   3  somministrazione/minuto   
...                ...    ...         ...  ..                      ...   
6683    BIANCONI CARLO      7        4264   5  somministrazione/minuto   
6731   GOVONE GIUSEPPE     29        7222   8  somministrazione/minuto   
6760  LODOVICO IL MORO     93        5290   6  somministrazione/minuto   
6811         SOLFERINO     12        1028   1  somministrazione/minuto   
6855   LOMBARDINI ELIA     14        5146   6  somministrazione/minuto   

     Forma commercio prev Forma vendita  \
1337     somministrazione      al banco   
1358     somministrazione      al banco   
1359     somministrazione      al banco   
1360               minuto      al banco   
1361     somministrazione         misto   
...                   ...           ...   
6683     somministrazione     al tavolo   
6731     somministrazione         misto   
6760     somministrazione         misto   
6811     somministrazione     al tavolo   
6855     somministrazione         misto   

                                     Settore storico pe  \
1337                     Ristorante, trattoria, osteria   
1358              BAR CAFFÿý;Tavola calda;Tavola fredda   
1359  Tavola fredda;BAR CAFFÿý;Bar gastronomici e si...   
1360                                         Ristorante   
1361  Pizzeria;Cibi cotti preconfezionati;Bar gastro...   
...                                                 ...   
6683  BAR CAFFÿý;Ristorante, trattoria, osteria;Gene...   
6731  BAR CAFFÿý;Gelateria;Trattoria;Ristorante, tra...   
6760  BAR CAFFÿý;Ristorante, trattoria, osteria;Trat...   
6811  Pizzeria;Ristorante, trattoria, osteria;Tratto...   
6855  LETT. GIOCHI LECITI + SOCIETA';Ristorante, tra...   

      Superficie somministrazione  
1337                         45.0  
1358                        184.0  
1359                         58.0  
1360                        112.0  
1361                         48.0  
...                           ...  
6683                        114.0  
6731                        